---
name: 'Setup poetry'
description: 'Set up a specific version of poetry and add the command-line executable to the PATH.'
inputs:
  poetry-version:
    description: "Exact poetry version to use."
    required: true
  virtualenvs-create:
    description: "Create a new virtual environment if one doesn't already exist."
    default: "true"
    required: false
  virtualenvs-in-project:
    description: "Create the virtualenv inside the project's root directory."
    default: "true"
    required: false
runs:
  using: composite
  steps:
    - name: Install
      run: |
        curl -O -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
        python get-poetry.py --yes --version=${{ inputs.poetry-version }}
        rm get-poetry.py
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
    - name: Configure
      run: |
        poetry config virtualenvs.create ${{ inputs.virtualenvs-create }}
        poetry config virtualenvs.in-project ${{ inputs.virtualenvs-in-project }}
      shell: bash