name: py-test

on:
  push:
    paths:
      - ".github/workflows/*"
      - "bin/*"
      - "boris/*"
      - "tests/*"
      - "poetry.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      SAM_CLI_TELEMETRY: 0
    strategy:
      matrix:
        python: [ "3.7", "3.8" ]
        include:
          - python: 3.7
            makefile_test_command: test_py37
          - python: 3.8
            makefile_test_command: test_py38
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: ./.github/actions/setup-poetry
        with:
          poetry-version: "1.1.4"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - uses: actions/cache@v2
        id: pipcache
        with:
          path: ~/.cache/pip
          key: pipcache-${{ matrix.python }}

      - run: python -m pip install aws-sam-cli --disable-pip-version-check

      - uses: actions/cache@v2
        id: pycache
        with:
          path: .venv
          key: pycache-${{ matrix.python }}-${{ hashFiles('poetry.lock') }}

      - run: poetry install
        if: steps.pycache.outputs.cache-hit != 'true'

      - run: make lint
      - run: make ${{ matrix.makefile_test_command }}
